name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_NAME: helloworld
  ECR_URL: 351222107032.dkr.ecr.us-west-2.amazonaws.com/helloworld
  CLUSTER: datree-demo
  CLUSTER_URL: https://7E980DD33204F2ECCED48D257ED048AB.gr7.us-west-2.eks.amazonaws.com
  KUBE_CERT: ${{ secrets.KUBE_CERT }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t foo .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1.3.1
        with:
          access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          local-image: foo
          image: ${ECR_NAME}:${{ github.sha }}
      - name: Update image tag
        run: export IMAGE_TAG=${{ github.sha }} && cat kubernetes-deploy.tpl | envsubst > kubernetes-deploy.yaml
      - name: Authenticate to the cluster
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${CLUSTER} --certificate-authority=./ca.crt --server=${CLUSTER_URL}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${CLUSTER} --cluster=${CLUSTER} --user=deploy-user
          kubectl config use-context ${CLUSTER}
      - name: Apply the updated manifest
        run: |
          kubectl apply -f kubernetes-deploy.yaml
